Repository 10up/simple-podcasting, pull requests merged in 2018-11, with the labels that each got.

#49 Fix/multiple block insert 45
  assets/js/blocks.js
  dist/js/blocks.min.js
  dist/js/blocks.min.js.map
Labels: bug

#52 Fix/removing term associations
  assets/js/blocks.js
  dist/js/blocks.min.js
  dist/js/blocks.min.js.map
  dist/js/podcasting-edit-post.min.js
  dist/js/podcasting-edit-post.min.js.map
  dist/js/podcasting-edit-term.min.js
  dist/js/podcasting-edit-term.min.js.map
Labels: bug

#51 Fix/audio player not working
  assets/js/blocks.js
  dist/js/blocks.min.js
  dist/js/blocks.min.js.map
Labels: bug

#56 Feature/add email to feed 55
  includes/customize-feed.php
  includes/datatypes.php
Labels: enhancement

#58 Adding language selector for podcasts
  includes/customize-feed.php
  includes/datatypes.php
Labels: enhancement

#53 Feature/descriptive help
  includes/datatypes.php
Labels: enhancement, question

#57 Fully clear new term form after submission #33
  assets/js/podcasting-edit-term.js
Labels: enhancement
